### ISSUE TITLE
write a configurator script

### ISSUE THREAD

**Issue by sciabarracom** [apache/openserverless#25]
Write a configurator script that will replace nuv configuratos that can be executed with bun such as:

`bun config.sh config.json` will execute a configuation like the one performed by `npm create svelte`

The configuration itself is sprecified by someting like this:

```
{
   "AWS_ACCESS_ID": {
      type: "string"
    },
    "AWS_VM_COUNT": {
       type: "int"
     } 
}
```

include the more common options for string, boolen, int, fixed lists, hidden password etc

it shold read the current confgurations (invoking nuv -config -d) and complete setting the configurations (invoking nuv -config A=b)

It should replace the configurator at the moment on nuv cloud eks config (and aks and gke and so on) with a single config.json

All the dependencies required should be donwloaded automatically

implement in a separate repo until we are read to include in openserverless-task

**Comment by dcremonini** [comment]
You can find the library **@clack/prompts** here https://www.npmjs.com/package/@clack/prompts

There is also a demo here https://stackblitz.com/edit/clack-prompts?file=index.js

Hope this helps.

**Comment by sciabarracom** [comment]
contribute a PR to be usable as $OPS util config <config.json> with bun storing the result in an attribute

add tests under `ops tests`
