### ISSUE TITLE
discuss versions

### ISSUE THREAD

**Issue by sciabarracom** [apache/openserverless#30]
Here there is a draft standard for the versioning, please review it and comment here before we commit it.

https://github.com/sciabarracom/openserverless/blob/main/VERSIONS.md

**Comment by pjfanning** [comment]
I don't like the date in the version. Reproducible Builds are becoming the norm and having the date popping into the version number or getting compiled into binary artifacts is an issue.

**Comment by d4rkstar** [comment]
I read the whole draft: it's ok for me.
I would add that the use of the time stamp, although it does not provide information on the nature of the release, can however provide indications of when a version was created. In particular for runtimes, where it could happen to release a new image for an older runtime, I think it could be useful. Among other things, its use alongside the semver is not excluded.
