### ISSUE TITLE
migrate the nuv ide to ops ide

### ISSUE THREAD

**Issue by sciabarracom** [apache/openserverless#34]
Migrate the exiting  `nuv ide` tasks to `ops ide` performing the following chanages:
- rewrite the `pyhton` code in `js` with bun code
- change nuvfile to opsfile and nuvopts to docopts
- change any internal reference to nuv to $OPS 
- replace any grep in rg
- use the new tools (coreutils)

**Comment by d4rkstar** [comment]
Hello,
I've a question about the task `ide login`.

In nuv there are some hardcoded values and i need a strategy to port. 

In particular: how should we set `NUVDEV_APIHOST`, `NUVDEV_HOST` (ported these should be became `OPSDEV_APIHOST` and `OPSDEV_HOST`) ?

Here's the olaris code: https://github.com/nuvolaris/olaris/blob/61562e1e05c51fd9b4900f15f5d839504d5fd749/ide/nuvfile.yml#L44
