### ISSUE TITLE
[Issue] Configure SSH for VSCode

### ISSUE THREAD

**Issue by saadmanrafat** [apache/openserverless#37]
multipass transfer $HOME/.ssh/id_rsa.pub openserverless:
multipass exec openserverless -- bash -c "cat id_rsa.pub | tee -a .ssh/authorized_keys"

throws 

[2024-08-08T15:20:12.154] [error] [sftp] cannot open local file /home/$USER/.ssh/id_rsa.pub: Permission denied

Kind of stuck here! Is there any way around this problem?

**Comment by sciabarracom** [comment]
How does throw this $USER if you do not use it in the command line

**Comment by saadmanrafat** [comment]
> How does throw this $USER if you do not use it in the command line!
no sorry it throws  /home/saadman/.ssh/id_rsa.pub: Permission Denied. 

A proper place to raise this issue would be on multipass github but I followed every single step on the how-to openserverless page. I thought it would provide more context and a little bit of help.

**Comment by sciabarracom** [comment]
Hi @saadmanrafat we released an updated version of the cloud-init, I just tried it and works.
