### ISSUE TITLE
Seeking Guidance on CLI Choice for Building a Serverless Python Application

### ISSUE THREAD

**Issue by saadmanrafat** [apache/openserverless#43]
I'm currently building a prototype and closely following the progress on the `ops` CLI. However, without proper documentation, navigating it has been challenging. I've been filling in the gaps by referencing Apache OpenWhisk, but I'm unsure if this approach is optimal.

Given my limited time to develop a complex serverless Python application, would you recommend using the `nuv` CLI or `ops` CLI at this stage?

I deeply appreciate the hard work and patience of the developers and maintainers. Please understand that I ask this question out of necessity, as I had no other appropriate forum to seek guidance. I apologize if this is not the ideal place to inquire.

**Comment by giusdp** [comment]
Since it seems you have some time constraints, it would be better to use the nuv CLI. 

The ops cli is in the middle of the migration phase to bring the project here and it's not feature complete.

There is also further documentation for that, which will eventually be moved here as well.

**Comment by saadmanrafat** [comment]
> Since it seems you have some time constraints, it would be better to use the nuv CLI.
> 
> The ops cli is in the middle of the migration phase to bring the project here and it's not feature complete.
> 
> There is also further documentation for that, which will eventually be moved here as well.

I'll switch to using the `nuv` CLI as recommended. And keep following these repositories during the transition. Looking forward to working with the updated setup!

Thank you!
