### ISSUE TITLE
Manage site "maintenance" / "coming soon" page from env

### ISSUE THREAD

**Issue by d4rkstar** [apache/openserverless#49]
Hello,
i would introduce inside the openserverless-site templates the parsing of an env variable called `HUGO_SITE_MAINT` (or something like..).

When this is set to `true`, all the routes are disabled and only the homepage with the "Coming Soon" message is displayed.
When unset (or set to `false`), the full website is displayed.

This can be useful to start the merge of the code on the main repository, allowing other members to work on it without searching the "latest code" on forks.

**Comment by francescotimperi** [comment]
+1

This would ease the introduction of new documentation steps, so I strongly support this type of feature.

**Comment by d4rkstar** [comment]
Hello,
i've implemented the feature.

If you look at the [Taskfile.yml](https://github.com/d4rkstar/openserverless-site/blob/8c737177933d614783cd543f281284928bf5c22b/Taskfile.yaml#L48) in the branch [issue_49](https://github.com/d4rkstar/openserverless-site/tree/issue_49) inside my fork, i've added an env variable called 
`HUGO_SITE_MAINT`.
When set to true a "COMING SOON" page is displayed.

You can see the live preview here: https://openserverless-demo.netlify.app/

However, to make available this code, i need to do a first big PR from my fork/branch to [openserverless-site/main](https://github.com/apache/openserverless-site).

Let me know if I can proceed.

**Comment by AntonioPiga** [comment]
+1

A great feature that speeds up and simplifies development
