### ISSUE TITLE
Task-util-config: add a step by step procedure that explains how to develop util/config/configurator/configurator.ts

### ISSUE THREAD

**Issue by dcremonini** [apache/openserverless#65]
- Kind of request: documentation request + enhancement: chore feature request

# Problem

As a developer, I cannot modify `configurator.ts` to submit a contribution.

Details:
- The source code is written in TypeScript, and it comes with some automatic tests.
- The TypeScript code is transpiled to a javascript file called `configurator.js`.
- The software development lifecycle of the `configurator.ts` is not documented.
- The transpiling of the source code `configurator.ts` to `configurator.js` is not in the CI/CD.

# Impact
Contributors who contribute to the Open Serverless installer.

# Priority
middle

# Expected outcome

1. A document is added along the source code to allow independent contribution for the `configurator.ts` application.
  - How to transpile.
  - How to run tests.
  - How to run with and without **bun**.
3. The transpiling process is automated in the CI/CD.
  - transpiling.
  - testing (a warning message at this stage is enough, at this stage I see no need to block the process if this step fails).

# Suggested solution
None

**Comment by giusdp** [comment]
Documentation on how to run and build was added. We can add a separate issue regarding a github action to build the configurator.
