### ISSUE TITLE
integrate a vector databases

### ISSUE THREAD

**Issue by sciabarracom** [apache/openserverless#78]
## Why you need it?
We need a vector database to support AI application

## How it could be?
Add the option to deploy a vector database in a multi tenant way and provide the secrets to the functions

## Other related information
Best option looks milvus:

https://github.com/milvus-io/milvus

It is multitenant, has kubernetes support, it is apache licensed and it is the most starred on github

worth to consider also:

https://github.com/qdrant/qdrant
https://github.com/weaviate/weaviate

**Comment by francescotimperi** [comment]
Indeed milvus seems to be the most reliable project currently. Idea it is to integrate the deployment via the miles k8s operator.

**Comment by d4rkstar** [comment]
Hello, i  agree on the fact that Milvus seems to be the right choice.

About the choice between Pulsar and Kafka, the first seems to be better (check [this article](https://medium.com/n11-tech/understanding-milvus-key-concepts-and-potential-applications-1fe4dedd7412) for more details).

About the deployment, i think that the third option is the best (Pulsar, existing minio, separate etcd)

I would add to take in consideration the [prerequisites for using Milvus](https://milvus.io/docs/prerequisite-docker.md). Raccomended are 4 cpu, 16/32GB ram and NVMe  drives.
