### ISSUE TITLE
remove stray copyright

### ISSUE THREAD

**Issue by pjfanning** [apache/openserverless#83]
https://github.com/apache/openserverless-operator/blob/e4a1acdf9f5c72d6008cb4df4af443cd61c12853/.github/workflows/image.yml#L18

A similar Nuvolaris LLC copyright was added to a similar file in the openserverless-streamer repo.

The Nuvolaris code was granted to the ASF so we shouldn't have Nuvolaris copright statements.

**Comment by francescotimperi** [comment]
Hi @pjfanning thanks for reporting this issue. A PR has been created for the opernserverless-operator project to fix the issue. Similarly we will fix under the openserverless-streamer

**Comment by francescotimperi** [comment]
The erroneous Nuvolaris LLC copyright notes have been removed.
